---
# Settings Config File
host:
    powercap:
        name: power_cap
        type: i
        default: 0
        min: 0
        max: 1000
        unit: watts
    bootflags:
        name: boot_flags
        type: s
        default: "default"
    sysstate:
        name: system_state
        type: s
        default: ""
    powerpolicy:
        name: power_policy
        type: s
        default: "ALWAYS_POWER_ON"
    restrictedmode:
        name: restricted_mode
        type: b
        default: false
    bootpolicy:
        name: boot_policy
        type: s
        default: "ONETIME"

